AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  sam-app

  Sample SAM Template for sam-app

Globals:
  Function:
    Timeout: 3
    MemorySize: 128
    Tracing: Active
    LoggingConfig:
      LogFormat: JSON
  Api:
    TracingEnabled: true

Resources:
  HelloWorldFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: hello_world/
      Handler: app.lambda_handler
      Runtime: python3.9
      Architectures:
      - x86_64
      Events:
        HelloWorld:
          Type: Api
          Properties:
            Path: /hello
            Method: get

  SamZooRegistryTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: SamZooRegistry
      AttributeDefinitions:
        - AttributeName: animalId
          AttributeType: S
      KeySchema:
        - AttributeName: animalId
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST

  PopulateZooRegistryFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: app.populate_zoo_registry
      Runtime: python3.9
      MemorySize: 128
      Timeout: 10
      Environment:
        Variables:
          TABLE_NAME: !Ref SamZooRegistryTable
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref SamZooRegistryTable
      CodeUri: sam_zoo_dummy/

Outputs:
  HelloWorldApi:
    Description: API Gateway endpoint URL for Prod stage for Hello World function
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"
  HelloWorldFunction:
    Description: Hello World Lambda Function ARN
    Value: !GetAtt HelloWorldFunction.Arn
  HelloWorldFunctionIamRole:
    Description: Implicit IAM Role created for Hello World function
    Value: !GetAtt HelloWorldFunctionRole.Arn
  ZooRegistryTableName:
    Description: "SamZooRegistry Table Name"
    Value: !Ref SamZooRegistryTable
